server.port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:testdb
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

